name: "BidMe: Close Bidding Period"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  close-bidding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Close bidding period
        run: bunx bidme close-bidding
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BIDME_PAT: ${{ secrets.BIDME_PAT }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

      - name: Commit archive and README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(bidme): update data"
